### ISSUE TITLE
Identify script language

### ISSUE THREAD

**Issue by cmmata** [CompSciLauren/awesome-git-hooks#11]
**Is your feature request related to a problem? Please describe.**
The readme has a list of scripts separated by git hook, but I can't see what language the script depends on without opening it.

**Describe the solution you'd like**
It could be nice to identify the language of the script (maybe a small icon next to the title), so people can see the requirements. For example, if we have a server that does not have perl installed, maybe we can't use a perl script.

**Comment by CompSciLauren** [comment]
Thanks for opening an issue! That makes sense, I can see how it would be helpful to have some sort of language indicator next to each script. I like your icons idea. I added icons on a development branch here: [language icons](https://github.com/CompSciLauren/awesome-git-hooks/tree/identify-script-language#readme)

Thinking about this issue made me realize that the script files could also be more clear about the language used. It says the language in the shebang at the top, but not everyone knows what that line means. I've added a "Requirements" description to each script, like this for example: [requirements comment](https://github.com/CompSciLauren/awesome-git-hooks/blob/identify-script-language/commit-msg-hooks/enforce-insert-issue-number.hook#L10)

Please take a look when you get the chance, and let me know what you think!

**Comment by CompSciLauren** [comment]
I originally placed the icons at the start of each script item, but it turns out that this is not allowed by the linter we use. I moved the icons to the end of each line and I think it looks good enough, and it complies with the linter requirements. Went ahead and merged this and the changes mentioned above into master, so I am closing this Issue. Feel free to comment on this if you have anything to add and we can always revisit this if needed. Thanks!

**Comment by cmmata** [comment]
I like the new icons! It's much clear than before. And having the requirements in the script description is a good point too, specially if there's a special requirement like works with python 3 but not 2. Thank you!
