### ISSUE TITLE
Add new hook manager

### ISSUE THREAD

**Issue by igorkamyshev** [CompSciLauren/awesome-git-hooks#14]
Hello! Great project, thanks for it. I use lefthook for management git hooks, it is very fast and really nice hook manager. Can I add to this?

https://github.com/igorkamyshev/kamyshev.me.src/

**Comment by igorkamyshev** [comment]
ok ok

**Comment by CompSciLauren** [comment]
Hi @igorkamyshev, sorry for the late reply! Thank you for creating this issue. I've been exploring this idea of adding a hook manager to this project, and these are my thoughts on it.

I understand why a hook manager is useful for projects in general, but I don't really see how it would be useful in this particular case. I believe users come to this repo to copy hooks they want to use, and they paste them into their own projects. Therefore, a hook manager would not be useful unless they installed it on their own project rather than this repo.

If you or anyone else reading this thinks that a hook manager could still be beneficial, please feel free to re-open this issue or create a new issue. If you could explain why and how it would be beneficial, it would help me understand the reasoning and we can explore this idea further. Thanks again, I really appreciate your input!
